name: Build on DockerHub and Deploy to AWS
on:
  push:
    branches:
      - main
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          dockerfile: ./Dockerfile
          tags: lekandev1/cicdec2:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}
    - name: Set permissions for private key
      run: |
        echo "${{ env.AWS_PRIVATE_KEY }}" > newkeypair.pem
        chmod 600 newkeypair.pem
    - name: Pull Docker image
      run: |
        ssh -o StrictHostKeyChecking=no -i newkeypair.pem ubuntu@54.209.100.37 'sudo docker pull lekandev1/cicdec2:latest'
    - name: Stop running container
      run: |
        ssh -o StrictHostKeyChecking=no -i newkeypair.pem ubuntu@54.209.100.37 'sudo docker stop cicdec2 || true'
        ssh -o StrictHostKeyChecking=no -i newkeypair.pem ubuntu@54.209.100.37 'sudo docker rm cicdec2 || true'
    - name: Run new container
      run: |
        ssh -o StrictHostKeyChecking=no -i newkeypair.pem ubuntu@54.209.100.37 'sudo docker run -d --name cicdec2 -p 80:3000 lekandev1/cicdec2:latest'